### ISSUE TITLE
Wordmove keep asking for ssh pass inside VVV

### ISSUE THREAD

**Issue by khoavominhpham** [joeguilmette/ee-vvv-wordmove#3]
Hello, 

I already have ssh key set up and i can ssh to my staging server without password outside VVV.
However, when i try using Wordmove inside VVV like so:

`vagrant@vvv:/srv/www/mywebsite/htdocs$ wordmove push --all`

Wordmove keep asking for ssh pass. Everything else work just fine with pass.
Is there a way to get around this ?
Thank you.

**Comment by joeguilmette** [comment]
Hi Khao -

You need to send the SSH keys from VVV (not your computer) to the server you are pushing to: https://github.com/joeguilmette/ee-vvv-wordmove#actually-using-wordmove
